import type { LevelDef } from '../sim/types';
import { level } from './define';

// Easy: one new idea at a time. Made by a generator; levels.test.ts plays every one.
export const EASY: readonly LevelDef[] = [
  level(
    { id: 'free-ride', name: 'Free Ride', hint: 'Old ditches are already dug. Use them.' },
    [
      '.O...O......',
      '......***P..',
      '#=*****..#.#',
      '#=..........',
      '==.#.......#',
      'S......#....',
      '#......#.#..',
      '.......#....',
      '#......###..',
      '.......#....',
    ],
  ),
  level(
    { id: 'puddle-jump', name: 'Puddle Jump', hint: 'The pond fills up, then spills over.' },
    [
      '..****S.....',
      '..*.....####',
      '..u.........',
      'O.*.........',
      '..*.........',
      '..*..O......',
      '..P.........',
      '....O.......',
      '............',
      '............',
    ],
  ),
  level(
    {
      id: 'duck-pond',
      name: 'Duck Pond',
      hint: 'Lead the water through the pond. Just enough digs. Don’t waste any.',
      budget: 5,
    },
    [
      '............',
      '...........#',
      '...........#',
      '...........#',
      '...........#',
      '..S****u....',
      '.......u....',
      '.......u*...',
      '........P..#',
      '........#...',
    ],
  ),
  level(
    { id: 'fork-in-the-road', name: 'Fork in the Road', hint: 'One spring, two plants.' },
    [
      '...#........',
      '............',
      '..P**.##....',
      '....*.....#O',
      '....*.......',
      '..O#S*****..',
      '.........P..',
      '...#........',
      '............',
      '......O.....',
    ],
  ),
  level(
    {
      id: 'plug-the-leak',
      name: 'Plug the Leak',
      hint: 'An old ditch leaks into a hole. Fill it in. Join your ditch to the old one.',
    },
    [
      '.........#..',
      '.........#..',
      '.........#..',
      '.........#..',
      '.........#..',
      '###.....P#..',
      '..S*****=#..',
      '........x#..',
      '........O#..',
      '..u.........',
    ],
  ),
  level(
    { id: 'watering-can', name: 'Watering Can', hint: 'A few digs to spare.', budget: 15 },
    [
      '............',
      '............',
      '#...........',
      '......*****P',
      '....O.*.....',
      '#.#..**.....',
      '#.****.....#',
      '##*.......#.',
      '#.*.........',
      '#.S......#..',
    ],
  ),
  level(
    { id: 'fill-and-spill', name: 'Fill and Spill', hint: 'Water fills the pond, then flows on.' },
    [
      '.S**........',
      '...uuu...#..',
      '...uuu.O.#..',
      '..=uu....##.',
      '...*........',
      '##.*#######.',
      '...******...',
      '........*...',
      '........P...',
      '.O..........',
    ],
  ),
  level(
    { id: 'seed-bank', name: 'Seed Bank', hint: 'Plan before you dig.', budget: 15 },
    [
      '.........#..',
      '............',
      '.O.....O.**S',
      '........**..',
      '....*****..#',
      '....*...##O.',
      '...#*.....#.',
      '..O.*#..u...',
      '...P*.#.....',
      '.....#...#..',
    ],
  ),
  level(
    { id: 'holey-moley', name: 'Holey Moley', hint: 'Keep your ditch away from holes.' },
    [
      '..S**.O.P...',
      '....**.**...',
      '.....***....',
      '..#.........',
      '#######.####',
      '............',
      '............',
      '........O...',
      '............',
      '...#........',
    ],
  ),
  level(
    { id: 'drip-drop', name: 'Drip Drop', hint: 'One old ditch runs to a hole. Block it.' },
    [
      '............',
      '....O.......',
      '.....Sx=....',
      '#.O.**.O....',
      '#..**.......',
      '#***......O.',
      '**..........',
      '*...........',
      '*...........',
      'P...........',
    ],
  ),
  level(
    { id: 'old-paths', name: 'Old Paths', hint: 'Some digging is already done.' },
    [
      '.#...**P....',
      '.#...*......',
      '.#*===..#.==',
      '***........O',
      '*#..........',
      '*#.....O....',
      '*..#........',
      '*#..........',
      '*#..#.......',
      'S#..#.......',
    ],
  ),
  level(
    { id: 'grandpas-ditch', name: 'Grandpa’s Ditch', hint: 'Old ditches are already dug. Use them.' },
    [
      '..O..#......',
      '.......**==S',
      '...O#O.*....',
      '..###.**....',
      '....#**.....',
      '....#*......',
      'P*****....#.',
      '............',
      'uu..........',
      'uu..........',
    ],
  ),
  level(
    { id: 'lily-pad', name: 'Lily Pad', hint: 'The pond fills up, then spills over.' },
    [
      '............',
      '............',
      '.**********S',
      '.*........#.',
      'uu....######',
      'uu........#.',
      '*.........#.',
      '*...........',
      '*...........',
      'P..........#',
    ],
  ),
  level(
    { id: 'froggy-stop', name: 'Froggy Stop', hint: 'Lead the water through the pond. Dig around the rocks.' },
    [
      '.....S****#.',
      '..#......*.#',
      '.....####*..',
      '......O.#*..',
      '.....#.uu*..',
      '.......uu...',
      '.....O#*....',
      '.....#.P.O..',
      '...###......',
      '...#.#..###.',
    ],
  ),
  level(
    { id: 'rocky-road', name: 'Rocky Road', hint: 'Rocks are in the way. A few digs to spare.', budget: 12 },
    [
      '..==...P**..',
      '.u.......*..',
      '.u.......*..',
      '.........*..',
      '......###*..',
      '.........*..',
      '......uu.*..',
      '..==..uu.*.O',
      '.........**.',
      '..........S.',
    ],
  ),
  level(
    { id: 'sneaky-leak', name: 'Sneaky Leak', hint: 'Find the leak and fill it with sand.' },
    [
      '.........#..',
      '......O.#.#=',
      '......=....=',
      '...#..x....=',
      '.P*****#.#.=',
      '......***#..',
      '........*.O#',
      '...#....*#..',
      '........***S',
      '............',
    ],
  ),
  level(
    { id: 'pond-hop', name: 'Pond Hop', hint: 'Water fills the pond, then flows on. Join your ditch to the old one.' },
    [
      '....*****P..',
      '....*......#',
      '....*.......',
      '....*......#',
      '....u.......',
      '....*.......',
      '....*.......',
      '....=.#.....',
      '....=.#.....',
      '....S.##....',
    ],
  ),
  level(
    { id: 'ready-made', name: 'Ready Made', hint: 'Some digging is already done. Every dig counts.', budget: 10 },
    [
      '...=.uu.....',
      '...=........',
      '...=.....=..',
      '.........=..',
      'S********=..',
      '.......u.=..',
      '.......u.=**',
      '.......u...P',
      '............',
      '............',
    ],
  ),
  level(
    { id: 'stone-wall', name: 'Stone Wall', hint: 'No digging through stone.' },
    [
      '....#.....#.',
      'S...#.....#.',
      '*...#.O...#.',
      '*.O.#..*****',
      '**..#***..#*',
      '.*****....#*',
      '..........#P',
      '..#########.',
      '..........#.',
      '..........##',
    ],
  ),
  level(
    { id: 'branch-out', name: 'Branch Out', hint: 'Split the ditch to reach both plants.' },
    [
      '..#.........',
      '..#...S...#P',
      '..#.********',
      '..#.*.......',
      '..#.*.......',
      '..##*....#..',
      '..#**....#..',
      '****.....#..',
      '*.#......#..',
      'P.#.#....#..',
    ],
  ),
  level(
    { id: 'boulder-bend', name: 'Boulder Bend', hint: 'Dig around the rocks.' },
    [
      '.....O......',
      '...........#',
      '.***********',
      '.*......#..*',
      '.*......#..*',
      '.*......#..P',
      '.*.#.O..#.==',
      '.*......#...',
      '.S......#O..',
      '..........O.',
    ],
  ),
  level(
    {
      id: 'splash-down',
      name: 'Splash Down',
      hint: 'The pond fills up, then spills over. Just enough digs. Don’t waste any.',
      budget: 12,
    },
    [
      '..O.........',
      '............',
      '.....#.***P.',
      '..O...uu....',
      '...***u.#...',
      '.***........',
      '#*#.......##',
      '.*..........',
      '.*......#.O.',
      '.S........#.',
    ],
  ),
  level(
    { id: 'split-stream', name: 'Split Stream', hint: 'One spring, two plants.' },
    [
      '............',
      '............',
      'O...P.......',
      '..******.O..',
      '..*..#.**...',
      '.#*.O.O.****',
      '.**#.......P',
      '#*..........',
      '.S..........',
      '...#.#......',
    ],
  ),
  level(
    { id: 'rose-bush', name: 'Rose Bush', hint: 'Plan before you dig.', budget: 21 },
    [
      'P*#....O.===',
      '.******..#..',
      '......****#.',
      '.........**#',
      '..........**',
      '.......O...*',
      '...O.....#.*',
      '...........*',
      '........#..*',
      '..#####....S',
    ],
  ),
  level(
    { id: 'half-done', name: 'Half Done', hint: 'Old ditches are already dug. Use them. Rocks are in the way.' },
    [
      '........#**S',
      'uuu.....#*..',
      'u.u.....#*..',
      '.......O#=..',
      '#########=##',
      '.#####****..',
      '.....#*.#...',
      'P****#*.#...',
      '....***.#...',
      '........#...',
    ],
  ),
  level(
    {
      id: 'patch-it-up',
      name: 'Patch It Up',
      hint: 'Water sneaks off to a hole. Plug the leak. A few digs to spare.',
      budget: 17,
    },
    [
      '............',
      'P********...',
      '........*...',
      '........*..O',
      '........*.O.',
      '....O...**..',
      '.........*..',
      '.....O...*.O',
      '.........Sx=',
      '............',
    ],
  ),
  level(
    {
      id: 'spade-work',
      name: 'Spade Work',
      hint: 'Plan before you dig. Split the ditch to reach both plants.',
      budget: 18,
    },
    [
      '............',
      '......#..P..',
      '.........*..',
      '......#..*..',
      '....=.#..*..',
      '#####.#..*.=',
      '....#.#..*..',
      '#...#.#****S',
      '#*******....',
      'P*..........',
    ],
  ),
  level(
    { id: 'hand-me-down', name: 'Hand-Me-Down', hint: 'Join your ditch to the old one. One spring, two plants.' },
    [
      'O...S.......',
      '#..#*.......',
      '.O..*#O.**P.',
      '....=..**...',
      '....==**....',
      '....==....##',
      '.***==......',
      '#*..#.......',
      'P*.#........',
      '...#....#...',
    ],
  ),
  level(
    { id: 'bathtub', name: 'Bathtub', hint: 'Lead the water through the pond. Split the ditch to reach both plants.' },
    [
      '........#*S#',
      '.......O.*.#',
      '.........*..',
      '.#*uu*uu**##',
      '..*#..uu.***',
      '..*#.......*',
      '..P#.......*',
      '...#...#...*',
      '#.#........*',
      '...........P',
    ],
  ),
  level(
    {
      id: 'swimming-hole',
      name: 'Swimming Hole',
      hint: 'Water fills the pond, then flows on. Holes everywhere. Find a dry path.',
    },
    [
      '........####',
      '............',
      '...O........',
      '....*****...',
      '..***...*...',
      'O.*...O.*...',
      '.**....uu**S',
      'P*.....uu...',
      '..O..O......',
      '............',
    ],
  ),
  level(
    { id: 'penny-pincher', name: 'Penny Pincher', hint: 'Few digs. Use the old ditches, they’re free.', budget: 14 },
    [
      '.....#.****S',
      '.######*....',
      '.....#**..O.',
      '.....#*..O..',
      '..#.***.....',
      '....*......O',
      '..#.*.......',
      'uuu#*.O.....',
      '..#.=.......',
      '....=P...#..',
    ],
  ),
  level(
    {
      id: 'leaky-lane',
      name: 'Leaky Lane',
      hint: 'Three old ditches leak. Fill them all. The pond fills up, then spills over.',
    },
    [
      '.#=O.....#..',
      '##=.....=O..',
      '.#x.#...x...',
      'P*********u*',
      '.......x...S',
      '#......O.#..',
      '==#.........',
      '.##########.',
      '............',
      '............',
    ],
  ),
  level(
    { id: 'gopher-town', name: 'Gopher Town', hint: 'Don’t dig next to a hole. No digging through stone.' },
    [
      'P*********..',
      '.........*..',
      '.....#...*.O',
      '.....#.#.**.',
      'O.#.#.#...**',
      '..#...#.#O.*',
      '..#.#.#...**',
      '#.#.#.#..#*.',
      '..#...###S*.',
      '..#.#....#..',
    ],
  ),
];
