import type { LevelDef } from '../sim/types';
import { level } from './define';

// Hard: many plants, tight budgets, leaks and detours together. Made by a generator; levels.test.ts plays every one.
export const HARD: readonly LevelDef[] = [
  level(
    {
      id: 'pothole-path',
      name: 'Pothole Path',
      hint: 'The short way passes a hole. Go around. It’s a long, twisty trip.',
    },
    [
      '.****.#####.',
      '.P..*.#.....',
      '..O.P*****..',
      '.........*..',
      '.....O...**S',
      '.........*..',
      '......O..*..',
      '....u..**P..',
      '...*****....',
      '...P..#P....',
    ],
  ),
  level(
    {
      id: 'shut-the-door',
      name: 'Shut the Door',
      hint: 'Find all three leaks and fill them in. Join your ditch to the old one.',
    },
    [
      '...........O',
      '.********..=',
      '.*......S..=',
      '.*...O.O..Ox',
      '.*.........P',
      '.*...O....**',
      '.*.O.....==.',
      '.**.....Ox=.',
      '..******.*=.',
      '.......***xO',
    ],
  ),
  level(
    { id: 'muddy-mending', name: 'Muddy Mending', hint: 'Three leaks to plug! So many holes! Stay clear of them.' },
    [
      '.=x******...',
      '#O.S....*.O.',
      '...*.O#x**..',
      '...**.#O.***',
      '....*.#....*',
      '....*.#....*',
      '..O.*.O#.O.*',
      '.O=x**#...#*',
      '.....*P..P**',
      '......#O....',
    ],
  ),
  level(
    {
      id: 'close-the-tap',
      name: 'Close the Tap',
      hint: 'Three old ditches leak. Fill them all. Few digs. The plants must share.',
      budget: 18,
    },
    [
      '............',
      '......O....O',
      '..P...=.....',
      '..*...=.....',
      '..*xO.=.O...',
      '..*...x..O..',
      '*********...',
      '*.....x.***P',
      '*....O=O....',
      'S.....O.....',
    ],
  ),
  level(
    {
      id: 'spring-cleaning',
      name: 'Spring Cleaning',
      hint: 'Find all three leaks and fill them in. Some digging is already done.',
    },
    [
      '.S.....O....',
      'x=****P.....',
      'O.*...***...',
      '..*.....*...',
      '..*.....P**P',
      '..*.....x.x.',
      'P**.....=.=O',
      '..*.....=...',
      '..P....O=...',
      '............',
    ],
  ),
  level(
    {
      id: 'patchwork-field',
      name: 'Patchwork Field',
      hint: 'Three leaks to plug! Water fills the pond, then flows on.',
    },
    [
      '=xS....#....',
      'O#*##.######',
      '#.*.#..P....',
      'P**#...*.O..',
      'x#u#...*....',
      '=.u*...*...O',
      '=O.**P**x===',
      '...*...*.O.#',
      '.#.*..#P....',
      '...P........',
    ],
  ),
  level(
    {
      id: 'shortcut',
      name: 'Shortcut',
      hint: 'Old ditches are already dug. Use them. Keep your ditch away from holes.',
    },
    [
      '............',
      '.......P....',
      '.***===***..',
      '.*...*...*..',
      '.*...P...*..',
      '.S..O.O..P..',
      '.*.....O....',
      '#*######.###',
      '.***P====***',
      '...........P',
    ],
  ),
  level(
    {
      id: 'leak-parade',
      name: 'Leak Parade',
      hint: 'Three old ditches leak. Fill them all. Join your ditch to the old one.',
    },
    [
      'u...........',
      'u..........O',
      '.********=x=',
      '.*..#####*..',
      '.*......#*..',
      'xP..O.S*#*x=',
      '=..O.O.***.O',
      '=.....**.uu.',
      '=O.P***.....',
      '=#..........',
    ],
  ),
  level(
    {
      id: 'double-trouble',
      name: 'Double Trouble',
      hint: 'Find all three leaks and fill them in. Few digs. The pond is free ditch.',
      budget: 17,
    },
    [
      '.........O..',
      'P.O..O....P.',
      '**x===O=x**.',
      '.*.......*..',
      '.*.......*..',
      '#*#######*##',
      '.*uuu*****..',
      '..*...x.....',
      '..S...=O....',
      '............',
    ],
  ),
  level(
    { id: 'the-plumber', name: 'The Plumber', hint: 'Three leaks to plug! Some digging is already done.', budget: 26 },
    [
      '..*P...P***.',
      '..*...O...*.',
      '..*.......*.',
      '..*.O...O.*.',
      '..*.......*.',
      '#x=*......*.',
      '#O.S***.O.*.',
      '#..#..**.**.',
      '#..#...***xO',
      '####..Ox....',
    ],
  ),
  level(
    {
      id: 'watch-your-step',
      name: 'Watch Your Step',
      hint: 'Holes everywhere. Find a dry path. The short way is blocked.',
    },
    [
      '*P......O...',
      '*..O...P....',
      '*#.....*.O.S',
      '*********.**',
      '#..*...#***.',
      '#..*...#.*..',
      '#..*.O.#*P..',
      '#..**.#P*.O.',
      '#...P..#....',
      '.......#....',
    ],
  ),
  level(
    {
      id: 'sand-in-the-cracks',
      name: 'Sand in the Cracks',
      hint: 'Find both leaks and fill them in. Old ditches are already dug. Use them.',
    },
    [
      '.....****S..',
      'O.====......',
      '.**..*..O#.#',
      '**...=...#..',
      'P.O.P=**.#..',
      '*..O..#*****',
      '*.....#*.#.*',
      '*.O...#*.#.P',
      'Px=...#P.#.#',
      'xO....####..',
    ],
  ),
  level(
    {
      id: 'no-drips-allowed',
      name: 'No Drips Allowed',
      hint: 'Three old ditches leak. Fill them all. The pond fills up, then spills over.',
    },
    [
      '......O=x*P.',
      '.........*..',
      '...P**P*uu..',
      '........uu..',
      '..O......*..',
      '.P...O...*..',
      '.****....*..',
      '..x.P****S..',
      '..O.x.......',
      '...O=.......',
    ],
  ),
  level(
    {
      id: 'leak-week',
      name: 'Leak Week',
      hint: 'An old ditch leaks into a hole. Fill it in. Every dig counts. Share one ditch.',
      budget: 18,
    },
    [
      '=O.......*P.',
      '=....#..P*.#',
      'x.#..u...*..',
      'S##..u...*..',
      '*#....O..*..',
      '***.....#*..',
      '.#*P*****P..',
      '..*.........',
      '..*.....#..#',
      '..P.........',
    ],
  ),
  level(
    { id: 'lean-lines', name: 'Lean Lines', hint: 'Few digs. Let the pond carry the water.', budget: 19 },
    [
      '.P.....*S..O',
      '.*.....*....',
      'uu**P***....',
      '*......*....',
      'P......*....',
      '#######*####',
      '.......*....',
      '.O...O.*....',
      '......***P..',
      '....P**.....',
    ],
  ),
  level(
    { id: 'no-wasted-sand', name: 'No Wasted Sand', hint: 'Few digs. Join up the old ditches.', budget: 21 },
    [
      '.P**#.......',
      '...**......O',
      '....*##*S#..',
      '....****..O.',
      '.....*....#.',
      '..O..*......',
      '.....P......',
      '.....=......',
      '***P*=*****P',
      'P...........',
    ],
  ),
  level(
    { id: 'cork-it', name: 'Cork It', hint: 'Plug the two leaks first. Join your ditch to the old one.' },
    [
      'O.P****.....',
      '......*..O.P',
      '...O=.*.O..*',
      '.O.#=.**...*',
      '....xO.*###*',
      '..*P=..*****',
      '..*.****...S',
      '..*....P.#Ox',
      '..P........=',
      '.......#...O',
    ],
  ),
  level(
    {
      id: 'just-enough',
      name: 'Just Enough',
      hint: 'Not enough digs for a ditch each. Take the long way round.',
      budget: 24,
    },
    [
      'P**...#.O.*P',
      '..P..O#..**.',
      '..*...#..*..',
      '..*...#..*..',
      '..*...###*..',
      '***S******..',
      '*.......*...',
      'P.......*...',
      '#.##.###P###',
      '............',
    ],
  ),
  level(
    {
      id: 'busy-beaver',
      name: 'Busy Beaver',
      hint: 'Find all three leaks and fill them in. So many holes! Stay clear of them.',
    },
    [
      '.==xP**##...',
      '.O....*P.O..',
      '....O..**...',
      '......O.*...',
      '...OxS..*...',
      '.O...****...',
      '...=x*..P...',
      '...O.*.O....',
      '..O..*.....=',
      '...P******P=',
    ],
  ),
  level(
    { id: 'little-shovel', name: 'Little Shovel', hint: 'Few digs. The pond is free ditch.', budget: 19 },
    [
      'P==**.......',
      '....*......#',
      '....*.......',
      '.#..P...***P',
      '....*...*...',
      '####*...*...',
      '.**P*u***...',
      '.*......P...',
      '.*...#......',
      '.S..........',
    ],
  ),
  level(
    {
      id: 'mend-and-tend',
      name: 'Mend and Tend',
      hint: 'Three leaks to plug! Few digs. The plants must share.',
      budget: 26,
    },
    [
      '.....O......',
      '......***...',
      '..*****#*#.O',
      '..S.x.#.*x==',
      '.O.O=#..*..O',
      '....O.#.*..x',
      '.....*******',
      '.P****.#...*',
      '#..########*',
      '#.........P*',
    ],
  ),
  level(
    {
      id: 'count-your-digs',
      name: 'Count Your Digs',
      hint: 'Few digs. Use the old ditches, they’re free. Rocks are in the way.',
      budget: 21,
    },
    [
      '............',
      '.P****.#O...',
      '..#..P.O#.#.',
      '.#...==#....',
      '......=***..',
      '#########*##',
      '.P*****..*..',
      '.####.***S..',
      '.O.#..*.....',
      '.#P***P.O...',
    ],
  ),
  level(
    {
      id: 'tiny-budget',
      name: 'Tiny Budget',
      hint: 'Every dig counts. Share one ditch. It’s a long, twisty trip.',
      budget: 25,
    },
    [
      '..P****#....',
      '.....#******',
      '.....#.*.#.P',
      '#######*####',
      '....S#**....',
      '..O.*#*#...#',
      '....****P***',
      '.....#*....P',
      '......P.....',
      '............',
    ],
  ),
  level(
    {
      id: 'frugal-farmer',
      name: 'Frugal Farmer',
      hint: 'Few digs. Join up the old ditches. Don’t dig next to a hole.',
      budget: 19,
    },
    [
      '............',
      '.#.....*S...',
      '...=..#*#...',
      '...=...*....',
      '..O.*P*****.',
      '...P*.....*.',
      '.***....O.*.',
      '.*...O....*.',
      '.P.......==P',
      '........#P..',
    ],
  ),
  level(
    {
      id: 'sharing-is-caring',
      name: 'Sharing Is Caring',
      hint: 'Few digs. Let the pond carry the water. No digging through stone.',
      budget: 19,
    },
    [
      '.........#P*',
      '..#..######*',
      '..#..P******',
      '.P#..=......',
      '.*#..=......',
      '.*#.P*......',
      '.*#..*......',
      '.**#.u......',
      '..P****.....',
      '......S#...#',
    ],
  ),
  level(
    {
      id: 'fix-the-fence',
      name: 'Fix the Fence',
      hint: 'Two old ditches leak. Fill them both. Not enough digs for a ditch each.',
      budget: 26,
    },
    [
      '...****.....',
      '***S##*....#',
      '*...##*.O..#',
      '*....#*x=..#',
      '*...#.*....#',
      '*...##*****P',
      '*...##*...*.',
      '*#####P...P.',
      '**#.#.xO....',
      '.P#.##......',
    ],
  ),
  level(
    {
      id: 'mole-hills',
      name: 'Mole Hills',
      hint: 'One old ditch runs to a hole. Block it. Few digs. The plants must share.',
      budget: 21,
    },
    [
      '...*S*****P.',
      '...*.....*..',
      '.O.*....#*.O',
      'Ox**.....**.',
      '.P*...O.O.*P',
      '..........*.',
      '..........P.',
      '..........*.',
      '.........#*.',
      '.......#=P*.',
    ],
  ),
  level(
    {
      id: 'one-ditch-wonder',
      name: 'One Ditch Wonder',
      hint: 'Few digs. The pond is free ditch. Holes everywhere. Find a dry path.',
      budget: 23,
    },
    [
      '............',
      '.P**........',
      '...*........',
      '.O.*......O.',
      'P..*...O...P',
      '***uu**.****',
      '*..*..***...',
      '*..P....S...',
      '*...O.......',
      'P.......O...',
    ],
  ),
  level(
    {
      id: 'muddy-basin',
      name: 'Muddy Basin',
      hint: 'Find the leak and fill it with sand. Few digs. Let the pond carry the water.',
      budget: 19,
    },
    [
      'O=..........',
      '.=..........',
      '.x.........P',
      '.P....P..O.=',
      '.*....*...==',
      '.u....*..*=.',
      '.*....*..*..',
      '.*********..',
      '.P..P....*..',
      '......O..S..',
    ],
  ),
  level(
    {
      id: 'pocket-change',
      name: 'Pocket Change',
      hint: 'Every dig counts. Share one ditch. The short way passes a hole. Go around.',
      budget: 26,
    },
    [
      '.P*********.',
      '....*.....P.',
      '....*.O.....',
      '....**.P.O..',
      '.....*.*....',
      '.....*.*....',
      '.....S***.O.',
      '........*..P',
      '........****',
      '........P...',
    ],
  ),
  level(
    {
      id: 'thirsty-ground',
      name: 'Thirsty Ground',
      hint: 'Find both leaks and fill them in. Few digs. The pond is free ditch.',
      budget: 13,
    },
    [
      '............',
      '....P....*P#',
      '....*u**P*..',
      '#...*....*..',
      '#.O.*....uuu',
      '...**....*..',
      '...S.....*P.',
      '.....O..#*xO',
      '.....===xP..',
      '...#........',
    ],
  ),
  level(
    {
      id: 'dusty-ditch',
      name: 'Dusty Ditch',
      hint: 'Plug the two leaks first. Few digs. Use the old ditches, they’re free.',
      budget: 17,
    },
    [
      '..O.........',
      'P*..........',
      '.*******S*==',
      '....P....x.=',
      'O.Ox*....=.=',
      '....*....O.*',
      '..P**......*',
      '....P###...*',
      '...O...#...*',
      '..#####....P',
    ],
  ),
  level(
    {
      id: 'skinny-ditch',
      name: 'Skinny Ditch',
      hint: 'Not enough digs for a ditch each. Keep your ditch away from holes.',
      budget: 24,
    },
    [
      '......****P#',
      '......*.....',
      '.....*S..O..',
      '.....*.O....',
      '.....*......',
      '.O...*......',
      '..P********P',
      '......*..*..',
      '######*##P..',
      '.#.P***.....',
    ],
  ),
  level(
    { id: 'burrow-alley', name: 'Burrow Alley', hint: 'Water sneaks off to a hole. Plug the leak.', budget: 15 },
    [
      '............',
      '...........P',
      '...........*',
      '.P*.......uu',
      'O.*......*u.',
      '..P....P.*..',
      '***=******.O',
      'P..x.....*S.',
      '...O........',
      '............',
    ],
  ),
];
