import type { LevelDef } from '../sim/types';
import { level } from './define';

// Medium: two or three ideas mixed. Made by a generator; levels.test.ts plays every one.
export const MEDIUM: readonly LevelDef[] = [
  level(
    {
      id: 'stop-the-drain',
      name: 'Stop the Drain',
      hint: 'Find all three leaks and fill them in. One spring, two plants.',
    },
    [
      '............',
      '.....P..#...',
      'uuu..*x==O..',
      '.....*..O.#.',
      '#....*...O..',
      '...=x*#.....',
      '...O.*..O...',
      '#####S##..#.',
      '.O==x***#u..',
      '...###.***P.',
    ],
  ),
  level(
    {
      id: 'bucket-with-a-hole',
      name: 'Bucket with a Hole',
      hint: 'Three leaks to plug! Some digging is already done.',
      budget: 11,
    },
    [
      '............',
      '..#.........',
      'O=#########.',
      '.=#.O=....#.',
      '.x###x..xO#.',
      '.****=**=.##',
      '.*......**P.',
      '#*########.#',
      'S*......#...',
      '........##..',
    ],
  ),
  level(
    { id: 'hungry-holes', name: 'Hungry Holes', hint: 'So many holes! Stay clear of them. Take the long way round.' },
    [
      '............',
      '.........O..',
      '...******.P.',
      '...*..#.***.',
      '...*..#O....',
      '...*.O..O.O.',
      '...**.......',
      '....********',
      '...........S',
      '..O.........',
    ],
  ),
  level(
    {
      id: 'big-puddle',
      name: 'Big Puddle',
      hint: 'Lead the water through the pond. The short way passes a hole. Go around.',
      budget: 18,
    },
    [
      '##.#......#.',
      '..S***......',
      '...#.*....#.',
      '..#..*.#.#O.',
      '..#..*...O.P',
      '.#...*.....*',
      '#....uu*.O.*',
      '.....u.**#**',
      '........***.',
      '...#...==###',
    ],
  ),
  level(
    { id: 'short-shovel', name: 'Short Shovel', hint: 'Few digs. The plants must share.', budget: 17 },
    [
      '..S****.....',
      '#.....*.....',
      '#.....*.....',
      '#.....*...#.',
      '......P...#.',
      '......*...#.',
      '######*#.###',
      '.O.O.**...#.',
      '....**..O.#.',
      'P****....=#.',
    ],
  ),
  level(
    {
      id: 'fix-it-farm',
      name: 'Fix-It Farm',
      hint: 'Three old ditches leak. Fill them all. A few digs to spare.',
      budget: 13,
    },
    [
      'O.O...O.....',
      '=..#........',
      '=..#...#....',
      'xO.#...#....',
      'P......#....',
      '*****S****..',
      'x.....x#.*..',
      'O....O=#.*..',
      '......O#.P..',
      '..........#.',
    ],
  ),
  level(
    {
      id: 'overflow',
      name: 'Overflow',
      hint: 'Water fills the pond, then flows on. Old ditches are already dug. Use them.',
      budget: 15,
    },
    [
      '.***S=====..',
      '.*...*......',
      'uu.O.*......',
      'u#O..*......',
      '*#...*...===',
      '*#...P......',
      '*#.......O..',
      '*#O.........',
      '*#..........',
      'P#..........',
    ],
  ),
  level(
    {
      id: 'old-ditch-trouble',
      name: 'Old Ditch Trouble',
      hint: 'Find all three leaks and fill them in. Holes everywhere. Find a dry path.',
    },
    [
      '...O=.O=....',
      '.=O.=..=....',
      '.x..x.O=....',
      '******.x....',
      'P....***.O..',
      '...O...**...',
      '........***S',
      '............',
      '............',
      '............',
    ],
  ),
  level(
    {
      id: 'the-long-way',
      name: 'The Long Way',
      hint: 'It’s a long, twisty trip. Split the ditch to reach both plants.',
    },
    [
      '......S.....',
      '######*#####',
      '.....#****..',
      '...P*#...*..',
      '....*#...*..',
      '.###*####*##',
      '...**#...*..',
      '...*.#...*..',
      '...*###..*..',
      '...********P',
    ],
  ),
  level(
    { id: 'seal-the-crack', name: 'Seal the Crack', hint: 'Three leaks to plug! Dig around the rocks.' },
    [
      '..#....O.=O.',
      '.O.....=O=..',
      '.#O##..=.=..',
      '..x.#..x.xO.',
      '.P**#*****..',
      '...*#*.#.***',
      '...*#*..#..*',
      '...***..#O.*',
      '........#..*',
      '..#.....###S',
    ],
  ),
  level(
    {
      id: 'paddling-pool',
      name: 'Paddling Pool',
      hint: 'The pond fills up, then spills over. Rocks are in the way.',
      budget: 22,
    },
    [
      '...P*****.O.',
      '........*S..',
      '.........*#.',
      '.........***',
      '###########*',
      'O.*****u****',
      '.**.........',
      '.P......#...',
      '............',
      '............',
    ],
  ),
  level(
    {
      id: 'swiss-cheese',
      name: 'Swiss Cheese',
      hint: 'So many holes! Stay clear of them. The short way is blocked.',
      budget: 25,
    },
    [
      '.......#....',
      '..*********.',
      '..*#####..*.',
      '..*.O.....*#',
      '..**......*.',
      '...*..####*.',
      '.#.*#O..O.*.',
      '#..**.uu..P.',
      '....**......',
      '.....S..O..O',
    ],
  ),
  level(
    { id: 'every-dig-counts', name: 'Every Dig Counts', hint: 'Few digs. Let the pond carry the water.', budget: 16 },
    [
      '...#..O.P...',
      '...#....*...',
      '...#....uuu.',
      '...#......*.',
      '...#.O#...*#',
      '#.....*****S',
      '.....#*..#..',
      '*******.....',
      'P.........#.',
      '.......#....',
    ],
  ),
  level(
    {
      id: 'drain-hunters',
      name: 'Drain Hunters',
      hint: 'Fill all three leaky ditches, then find a dry path past the holes.',
      budget: 17,
    },
    [
      '............',
      '.#.uuu####..',
      '.#.uuu......',
      '.#..........',
      '......O=O.O.',
      '....#..x...S',
      'Ox.O==x*****',
      '#P*..O.*....',
      '..*##.**....',
      '#.*****..###',
    ],
  ),
  level(
    { id: 'veggie-patch', name: 'Veggie Patch', hint: 'Five plants, one spring.' },
    [
      'O.P*........',
      '...*......*S',
      '...*......*.',
      '...*....O.*.',
      '...*P***..*.',
      '...*...*P**.',
      '...*......*.',
      '...*..O.#.P.',
      '...*....#...',
      '...P........',
    ],
  ),
  level(
    {
      id: 'thrifty-garden',
      name: 'Thrifty Garden',
      hint: 'Every dig counts. Share one ditch. No digging through stone.',
      budget: 22,
    },
    [
      'P*#...###...',
      '.*#.O.......',
      '.***.#.**S..',
      '..#*****....',
      '#######*####',
      '.*******....',
      '.*..#####...',
      '.*.#........',
      '.P..........',
      '............',
    ],
  ),
  level(
    {
      id: 'plugged-up',
      name: 'Plugged Up',
      hint: 'Find all three leaks and fill them in. Lead the water through the pond.',
      budget: 15,
    },
    [
      'P*******....',
      '.......*....',
      '..#####*.###',
      'O..Ox***#...',
      '.####*#.####',
      '...uu*.O#...',
      '...u*...#...',
      '....Sx==#...',
      '....x..O#..O',
      '...O=.......',
    ],
  ),
  level(
    {
      id: 'rabbit-warren',
      name: 'Rabbit Warren',
      hint: 'So many holes! Stay clear of them. Take the long way round.',
      budget: 25,
    },
    [
      '******......',
      '*....*......',
      '*.O..*......',
      '*....*S.....',
      '*....*.O....',
      '*.O..**.....',
      '*.....***...',
      'P.......*...',
      '.O......*...',
      '........P...',
    ],
  ),
  level(
    { id: 'tiptoe', name: 'Tiptoe', hint: 'Holes everywhere. Find a dry path. It’s a long, twisty trip.' },
    [
      '............',
      '....********',
      '....*......*',
      '#***S..O...*',
      '#*.........*',
      '.*.........*',
      '.*.O..O..O.*',
      '.**.......**',
      '..***.O...*.',
      '....P..uu.P.',
    ],
  ),
  level(
    {
      id: 'sinkholes',
      name: 'Sinkholes',
      hint: 'Keep your ditch away from holes. The short way is blocked.',
      budget: 30,
    },
    [
      '.***********',
      '.*.........*',
      '.S...O.O...*',
      '...........*',
      '######.####*',
      '....uuu....*',
      '.........O.*',
      '..........**',
      '...********.',
      '...P........',
    ],
  ),
  level(
    { id: 'old-trail', name: 'Old Trail', hint: 'Join your ditch to the old one. Water all five plants.' },
    [
      '....P...P...',
      '.P*****.*...',
      '......*****P',
      '......S.....',
      '...O..=.....',
      '.=O...=.....',
      '......=.....',
      '..O...=.....',
      '...***=...##',
      '.P**........',
    ],
  ),
  level(
    { id: 'pond-life', name: 'Pond Life', hint: 'Water fills the pond, then flows on. Some digging is already done.' },
    [
      '...#P.......',
      '...#*.......',
      '...#*...P...',
      '...#*.O.*...',
      '..P#u...*...',
      '..**u...*...',
      '...#u=P****S',
      '..O#*.......',
      '....*.......',
      '....P....#..',
    ],
  ),
  level(
    { id: 'zig-zag', name: 'Zig Zag', hint: 'Take the long way round. Five thirsty plants.' },
    [
      '#...#.....#.',
      '..O.#P......',
      '....#*.#....',
      '##..P*......',
      '##O.#*...O..',
      '#..O#**S*..O',
      'P**.#*..***.',
      '..**#*..#.**',
      '...P**#...#*',
      '..#.#.....#P',
    ],
  ),
  level(
    {
      id: 'small-spade',
      name: 'Small Spade',
      hint: 'Not enough digs for a ditch each. So many holes! Stay clear of them.',
      budget: 23,
    },
    [
      '.P**...P**.O',
      '...*.O...*..',
      '...**....*..',
      '....**.O.*..',
      '.....**.***.',
      '......***#*.',
      '.........#*.',
      '...O.....#*.',
      '..........S.',
      '............',
    ],
  ),
  level(
    {
      id: 'leak-detective',
      name: 'Leak Detective',
      hint: 'Three leaks to plug! Few digs. The plants must share.',
      budget: 17,
    },
    [
      '......*S....',
      '...#..*#....',
      'O=O..#*#....',
      '.x....*#....',
      '.******#....',
      '.*.#x.*#....',
      '.P.#O.*#....',
      'Ox.O#.****P.',
      '.#.........O',
      '..#......#..',
    ],
  ),
  level(
    { id: 'dam-it', name: 'Dam It', hint: 'Two old ditches leak. Fill them both. Five plants, one spring.' },
    [
      '.......O=...',
      'P#......=...',
      '*#......x...',
      '***********S',
      '...P..*.....',
      '...*..*.....',
      '...*..P.....',
      '.P**.O......',
      '...Px=......',
      '............',
    ],
  ),
  level(
    {
      id: 'tadpole-town',
      name: 'Tadpole Town',
      hint: 'The pond fills up, then spills over. It’s a long, twisty trip.',
    },
    [
      '....P.......',
      '....*.......',
      '....*.......',
      'P*****......',
      '.*...S**u...',
      '.*......*...',
      '.*......***P',
      '.*......*...',
      '.P......*...',
      '........P...',
    ],
  ),
  level(
    { id: 'head-start', name: 'Head Start', hint: 'Old ditches are already dug. Use them. Dig around the rocks.' },
    [
      '............',
      '...........P',
      '......P....*',
      '....****====',
      '...S*.......',
      'O=##*#######',
      '.=..*.......',
      '...*******P.',
      '...*#.*.....',
      'P===#.P....O',
    ],
  ),
  level(
    {
      id: 'tidy-the-ditches',
      name: 'Tidy the Ditches',
      hint: 'Three leaks to fill, and holes all around. Be careful!',
    },
    [
      '.S*******...',
      '.*...#..*#.O',
      '.*.O....**..',
      '.*..##.Ox*..',
      '.*#######*#.',
      '#***P#...*..',
      '#xx.##...*..',
      '#=O..#...P..',
      '#=...#....#.',
      '.O...#O===#.',
    ],
  ),
  level(
    { id: 'winding-river', name: 'Winding River', hint: 'The short way is blocked. Water all five plants.' },
    [
      '.....#****P.',
      '==...#*....=',
      '...S***....=',
      '...*.#*.....',
      '...*..*.....',
      '###*##P#####',
      '...*.#**....',
      'P****#.P....',
      '....P.O.....',
      '......###...',
    ],
  ),
  level(
    {
      id: 'tight-squeeze',
      name: 'Tight Squeeze',
      hint: 'Every dig counts. Share one ditch. Don’t dig next to a hole.',
      budget: 27,
    },
    [
      '*******.....',
      '*....#***S..',
      '*....#*...#.',
      '*....#*#..#.',
      '*....#*#..O.',
      '*....#*##...',
      '*....#****P.',
      '*....#......',
      '*....#......',
      'P....#......',
    ],
  ),
  level(
    { id: 'brim-full', name: 'Brim Full', hint: 'Lead the water through the pond. Take the long way round.' },
    [
      '......#P*...',
      '......#.*...',
      '...P..#.*...',
      'P***..#.**S.',
      '...uu*#.*...',
      'O....*#.*...',
      '.....****...',
      '........*...',
      '........P**P',
      '..uu........',
    ],
  ),
  level(
    { id: 'share-and-save', name: 'Share and Save', hint: 'Not enough digs for a ditch each.', budget: 13 },
    [
      '..........#.',
      'P***........',
      '...*..P...#.',
      '...*P**...#.',
      '...*..*...#.',
      '...P..P**.#.',
      '........*.#.',
      '........*.#.',
      '........S...',
      '............',
    ],
  ),
  level(
    {
      id: 'dry-maze',
      name: 'Dry Maze',
      hint: 'Fill the ditch that runs into the hole, then find the long way round.',
      budget: 22,
    },
    [
      '............',
      '.Sx=O#......',
      '.*...#..O...',
      '.*####..#...',
      '**...#..#*P.',
      '*.O..#..#*..',
      '*....O..#*..',
      '*###.####*..',
      '***********P',
      '............',
    ],
  ),
];
